### ISSUE TITLE
Failed to launch Minecraft after downloading

### ISSUE THREAD

**Issue by ddr3579** [LunaPixelStudios/Better-Minecraft-PLUS#8]
### Describe the Bug

Failed to launch world after downloading in multiMC

Computer specs:
RTX2080
I7-10700KF
64gb ram
12gb allocated to instance

Installed on Samsung NVME
Monitor: Samsung G9 5120x1440 240hz (idk if this matters)

Newest version of forge 36.2.26
[https://paste-bin.xyz/36427](url)

Forge 36.2.23 (default)
[https://paste-bin.xyz/36428](url)

I noticed the errors were different. The newest version almost seems to just freeze while the default version has a lot more critical errors. I also redownloaded both Java 18 & Java 17. I recently I have played your mod pack Better Minecraft 1.18.1, 17.1, & 16.5 so I don't believe it is an issue with Java or my hardware but I could be wrong. 

### Reproduction Steps

1. Downloaded mod pack using MultiMC 
2. Launched (both offline and online do the same thing)
3. Error
...

### Crash Report or Log

https://paste-bin.xyz/36427

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better Minecraft Plus

### Optifine

No

### Other Mods

no

**Comment by switchnlade** [comment]
Please try using Java 8 312 or below, not the 320s since they have a change that breaks forge at the moment which hasn't been patched from what I know of. You can get it from Adoptium's java 8 page. You'll have to scroll down a wee bit to get it: https://adoptium.net/archive.html?variant=openjdk8&jvmVariant=hotspot. I noticed a lot more errors in the log while launching with java 17.0.1 than I did with 8.

**Comment by switchnlade** [comment]
Looking at the 36.2.26 log, it may be related to this [issue](https://github.com/LunaPixelStudios/Better-Minecraft/issues/82#issuecomment-1028450208) since it has the same cutoff point. No idea if it would apply to a client to since this was reported on a server, but worth a shot.

note: the 36.2.23 log is from a change in 17.0.2 and the 320s of java 8. broke those forge versions. Guess the latest one fixed it up possibly.

**Comment by ddr3579** [comment]
I tried the easy way and just disabling bountiful, then it got hitched up on Farmers delight, I removed everything from farmers delight and it stopped at buzzier bee's. I assume it will keep getting caught up and this isn't really narrowing down the problem, However it was interesting that it Minecraft did boot after removing farmers delight however, it only said there was an issue loading the mods for it.

**Comment by switchnlade** [comment]
So it's working after removing farmer's delight? This error gets more confusing each time.

**Comment by ddr3579** [comment]
No, I just found it strange that Minecraft loaded without it, I can hear the music however this page comes up [https://imgur.com/a/ebCzjhO](url) then after removing those mods Minecraft refuses to open and i get this [https://paste-bin.xyz/36432](url) so it gets caught up on Upgrade Aquatic. After I remove Upgrade Aquatic it gets caught on Buzzier Bees and I assume it will just keep going down the list of mods until there are none

**Comment by SharkieTV** [comment]
Can you try another launcher like GDLauncher or CurseForge launcher?

**Comment by ddr3579** [comment]
CursedForge launcher fixed it. I've been dreading downloading another launcher but I guess it works better then MultiMC so time for a replacement. Thanks, hopefully this all somehow helps other people figure out their problems.

**Comment by ddr3579** [comment]
Something I did just notice and maybe this can help you guys, CursedForge launcher only lists 299 mods but a clean install on MultiMc lists 305 mods [https://imgur.com/a/bKSF49E](url)

**Comment by switchnlade** [comment]
Mod count is the same, I just checked my installs. At least it's fixed for you.
